SUPABASE_URL = "https://yjxosxkfskshkdegxmzh.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqeG9zeGtmc2tzaGtkZWd4bXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MzY1NjYsImV4cCI6MjA3ODMxMjU2Nn0.0uiLQWj5UvVihEeRWYQ9Bt9tnAvuHGEGAd4-e26Nlm8"
